services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_DB=authdb
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
      - rabbitmq

  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     # This tells the Next.js app (running in the browser) where the backend API is accessible
  #     - NEXT_PUBLIC_API_URL=http://localhost:8080
  #   depends_on:
  #     - auth-service # Ensure auth service starts first

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: authdb
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  db_data:
