services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_DB=authdb
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - JWT_SECRET=N4fK9z$B&E)H@McQfTjWnZr4u7x!A%D* # Added JWT Secret
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/ # Added for local RabbitMQ
      # - SERVICEBUS_CONNECTION_STRING=${SERVICEBUS_CONNECTION_STRING} # Removed for local dev, use RABBITMQ_URL instead
    depends_on:
      - db
      - rabbitmq

  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq

  # DEPRECEATED: Uncomment if you want to use the task service
  # task-service:
  #   build: ./task-service
  #   ports:
  #     - "8081:8081" # Expose task-service on port 8081
  #   environment:
  #     - TASK_SERVICE_PORT=8081
  #     - TASK_DB_HOST=taskdb # Service name of the task database
  #     - TASK_DB_PORT=5432 # Internal port for postgres
  #     - TASK_DB_USER=taskuser
  #     - TASK_DB_PASSWORD=taskpassword
  #     - TASK_DB_NAME=taskdb
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/ # For later event publishing
  #     - JWT_SECRET=N4fK9z$B&E)H@McQfTjWnZr4u7x!A%D* # Added JWT Secret (MUST MATCH auth-service)
  #   depends_on:
  #     - taskdb
  #     - rabbitmq

  calendar-service:
    build: ./calendar-service
    ports:
      - "8082:8082" # Expose calendar-service on port 8082
    environment:
      - CALENDAR_SERVICE_PORT=8082
      # Construct DATABASE_URL from individual parts for pgxpool
      - DATABASE_URL=postgres://calendaruser:calendarpassword@calendardb:5432/calendardb?sslmode=disable
      - JWT_SECRET=N4fK9z$B&E)H@McQfTjWnZr4u7x!A%D* # MUST MATCH auth-service
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/ # For potential future events
    depends_on:
      - calendardb
      - rabbitmq

  event-service:
    build: ./event-service
    ports:
      - "8083:8083" # Expose event-service on port 8083
    environment:
      - EVENT_SERVICE_PORT=8083
      # Construct DATABASE_URL from individual parts for pgxpool
      - EVENT_DB_URL=postgres://eventuser:eventpassword@eventdb:5432/eventdb?sslmode=disable
      - JWT_SECRET=N4fK9z$B&E)H@McQfTjWnZr4u7x!A%D* # MUST MATCH auth-service
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/ # For potential future events
    depends_on:
      - eventdb
      - rabbitmq

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     # This tells the Next.js app (running in the browser) where the backend API is accessible
  #     - NEXT_PUBLIC_API_URL=http://localhost:8080
  #   depends_on:
  #     - auth-service # Ensure auth service starts first

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: authdb
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # DEPRECEATED: Uncomment if you want to use the test database
  # test-db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: username
  #     POSTGRES_DB: testdb
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5433:5432"

  # DEPRECEATED: Uncomment if you want to use the test database
  # taskdb: # Database for the task service
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: taskuser
  #     POSTGRES_DB: taskdb
  #     POSTGRES_PASSWORD: taskpassword
  #   ports:
  #     - "5434:5432" # Map to host port 5434 to avoid conflicts
  #   volumes:
  #     - taskdb_data:/var/lib/postgresql/data

  calendardb: # Database for the calendar service
    image: postgres:latest
    environment:
      POSTGRES_USER: calendaruser
      POSTGRES_DB: calendardb
      POSTGRES_PASSWORD: calendarpassword
    ports:
      - "5435:5432" # Map to host port 5435
    volumes:
      - calendardb_data:/var/lib/postgresql/data

  eventdb: # Database for the event service
    image: postgres:latest
    environment:
      POSTGRES_USER: eventuser
      POSTGRES_DB: eventdb
      POSTGRES_PASSWORD: eventpassword
    ports:
      - "5436:5432" # Map to host port 5436
    volumes:
      - eventdb_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  db_data:
  taskdb_data: # Volume for taskdb persistence
  calendardb_data: # Volume for calendardb persistence
  eventdb_data: # Volume for eventdb persistence
