services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_DB=authdb
      - POSTGRES_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: authdb
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data: