services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_DB=authdb
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
      - rabbitmq

  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: authdb
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data: