name: Auth Service CI/CD

on:
  push:
    branches:
      - dev
    paths:
      - "auth-service/**"
      - ".github/workflows/auth_service_ci_cd.yml" # Trigger if workflow itself changes

jobs:
  test:
    name: Test Auth Service
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21" # Use the Go version appropriate for your project

      - name: Run tests
        run: |
          cd auth-service
          go test ./...

  build_and_push:
    name: Build and Push Auth Service Image
    runs-on: ubuntu-latest
    needs: test # Run only if the 'test' job succeeds
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }} # e.g., cozygoacrankjfr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service # Path to the Dockerfile directory
          file: ./auth-service/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/auth-service:latest # Tag image with ACR server and 'latest'
